[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gps-parser"
version = "0.1.0"
description = "GPS parser"
requires-python = ">=3.11"

[tool.setuptools]
py-modules = ["gps_parser"]